server:
  tomcat:
    accesslog:
      enabled: true
  port: 4014
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    protocol: TLS
    keyAlias: springboot-ssl
